### ISSUE TITLE
VideoDecoder close method is not working correctly

### ISSUE THREAD

**Issue by jimmyn** [ennuicastr/libavjs-webcodecs-polyfill#10]
VideoDecoder `close` method does not seem to be working, Even after close it keeps decoding frames and calling `output` callback.

The issue could be reproduced here - https://github.com/jimmyn/libavjs-webcodecs/

To run it:

```
- npm install
- npm start
```

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/5391775/221430981-25bbcd47-7adc-4cec-93c7-9a60361f3369.png">

**Comment by Yahweasel** [comment]
This is true, but it's also documented in the README:

```
Certain events are supposed to eagerly halt the event queue, but
LibAVJS-WebCodecs-Polyfill always lets the event queue finish.
```

I wasn't specific there about what those events are, but basically they're explicit closing and errors.

Is this happening even if you haven't already queued up data to decode? It should be that anything that's already queued up keeps on pumping out, but anything after you call close() is refused.

The long story short is that while this is indeed the case, it was an intentional compromise to keep the architecture a bit simpler. Is it particularly problematic somewhere?

**Comment by jimmyn** [comment]
@Yahweasel thanks for clarification, in my case it just consumes resources, but I think I can work around that. Good to know
