### ISSUE TITLE
Config types should restrict codec using string literals

### ISSUE THREAD

**Issue by stevenwaterman** [ennuicastr/libavjs-webcodecs-polyfill#2]
Currently when configuring an audio decoder the `codec` is typed as `string`. However, if it is not one of the codecs listed in [the spec](https://www.w3.org/TR/webcodecs-codec-registry/#audio-codec-registry) then `.isSupportedConfig` [throws a type error](https://w3c.github.io/webcodecs/#dom-audiodecoder-isconfigsupported). This could be prevented by typing it as a union of string literals instead.

https://github.com/ennuicastr/libavjs-webcodecs-polyfill/blob/401a3876600a891907816321f3f67496c84eca56/src/audio-decoder.ts#L369

**Comment by Yahweasel** [comment]
This is quite correct, but also I do no sensible checking of the codec string at all. To comply to the spec, I also need to check for the details part, which I literally just scrub off right now :) . Since dealing with the codec string in any sensible way is a TODO/FIXME right now, I don't think this is a critically important thing to fix for the moment.

**Comment by Yahweasel** [comment]
This is fixed by full codec string parsing in c53f74a.
